// Auto-generated by scripts/create-test-token.ts
import { PublicKey } from '@solana/web3.js';

/**
 * Test SPL Token for Vault deposits/withdrawals on Devnet
 */
export const TEST_TOKEN_MINT = new PublicKey('Hz4nonZiwcq4vPcFmnRUQ473XYftkwPz6F6Nz5zT1NpS');

export const TOKEN_CONFIG = {
  mint: TEST_TOKEN_MINT,
  decimals: 6,
  symbol: 'CHRONOS',
  name: 'CHRONOS Test Token',
} as const;
